# Generated by Django 2.1.3 on 2018-11-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1_score', models.PositiveSmallIntegerField()),
                ('player_2_score', models.PositiveSmallIntegerField()),
                ('draws', models.IntegerField()),
                ('player_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_organizer.Player')),
                ('player_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='event_organizer.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_beginning', models.DateTimeField()),
                ('date_ending', models.DateTimeField()),
                ('how_many_players', models.ManyToManyField(to='event_organizer.Player')),
            ],
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_organizer.Tournament'),
        ),
    ]
