# Generated by Django 2.1.3 on 2018-11-30 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0002_auto_20181129_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='how_many_players',
            new_name='players',
        ),
        migrations.AlterField(
            model_name='match',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='event_organizer.Player'),
        ),
    ]
