# Generated by Django 2.1.3 on 2018-11-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0003_auto_20181130_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='mtg event', max_length=255),
        ),
    ]
