# Generated by Django 2.1.3 on 2019-03-18 22:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0008_auto_20181230_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_expired', models.BooleanField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='event_organizer.Player')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ('date_beginning',)},
        ),
    ]
