# Generated by Django 2.1.3 on 2019-03-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0009_auto_20190318_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='player_id',
        ),
        migrations.AddField(
            model_name='token',
            name='player',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='event_organizer.Player'),
            preserve_default=False,
        ),
    ]
